# Define a porta padrão do MQTT
listener 1883

# Permite conexões sem usuário e senha (APENAS PARA DESENVOLVIMENTO)
allow_anonymous true

# Configurações de log para monitorar o tráfego
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log